### ISSUE TITLE
Import into GEMOC studio leads to Errors.

### ISSUE THREAD

**Issue by timKraeuter** [MatiasVara/BCOoLExamples#9]
I wanted to run the examples mentioned on the [GMCO webpage](https://gemoc.org/BCOoL/index.html#bcoolfirstexample) but I seem to be missing some bundles/dependencies.

Steps to reproduce:
1. Download the newest version of [GMCO studio](https://gemoc.org/download.html) --> V3.3.0 - 2021/07/28
2. Clone this repository.
3. `File < Import < Existing Projects into Workspace` to load the cloned samples.

Here is a screenshot of some errors:
![Skjermbilde 2021-09-07 115519](https://user-images.githubusercontent.com/21026858/132325702-16a120d3-9f0c-49c7-b7f0-40dbf2a2e1bf.png)

Can you give me a hint on how to resolve these errors? I would really like to try the BCOooLExamples myself.

Thanks in advance!

**Comment by MatiasVara** [comment]
Hello and thanks for the interest in BCOoL,

I would like to help you to try it but I am afraid that the current version of GEMOC studio does not include BCOoL. Also, there were many changes in plugins that BCOoL depends on so I think the integration may take some time. I haven't spent time on this project for a while so I am not really sure about the required amount of work. I think Julien De Antoni may know better than me (julien.deantoni@inria.fr). If you are interested on work on such a port, I would be happy to help.

**Comment by timKraeuter** [comment]
Thanks for the reply. Porting it to the current version sounds interesting but I am just trying to evaluate it for now.
Is it possible to use an older version of GEMOC studio to run the examples? Maybe [V1.0.0](https://gemoc.org/studio_releases/eclipse_package/2015/06/03/v1.0.0.html) from 2015?
Unfortunately, it does not seem to be available.

**Comment by MatiasVara** [comment]
GEMOC from the beginning of 2016 should be fine but I couldn't find it either.

**Comment by timKraeuter** [comment]
I am now using version 2.0.1 but I still have some errors:
![Skjermbilde 2021-09-09 143122](https://user-images.githubusercontent.com/21026858/132686067-8ffd63da-6dd1-4edb-98d4-4e158209e664.png)
Otherwise, I would like to watch the youtube videos about BCool. But they seem to be private as well.

**Comment by MatiasVara** [comment]
> I am now using version 2.0.1 but I still have some errors:
> ![Skjermbilde 2021-09-09 143122](https://user-images.githubusercontent.com/21026858/132686067-8ffd63da-6dd1-4edb-98d4-4e158209e664.png)

I think I can recognize some of those errors. Can you share with me that GEMOC studio? I will try to fix them and let you know.

> Otherwise, I would like to watch the youtube videos about BCool. But they seem to be private as well.

Thanks a lot for your comments, I just made them public. You can find them on my youtube channel at https://www.youtube.com/channel/UC46_R99E9R7yrz-ORiyHE8w/featured

**Comment by timKraeuter** [comment]
I downloaded it from here: http://gemoc.irisa.fr/pub/studio/gemoc_studio_2016_01_13/gemoc_studio-win32.win32.x86_64.zip
(https://gemoc.org/studio_releases/eclipse_package/2016/01/13/v2.0.1.html)

**Comment by MatiasVara** [comment]
Cool, I will try and let you know. I remember that I did many changes at the end of February 2016 so I think I will pick the version from the beginning of March, i.e., gemoc_studio_2016_03_16.

**Comment by MatiasVara** [comment]
Also, I just figured out that I had the old website at https://matiasvara.github.io/bcool.

**Comment by timKraeuter** [comment]
Thanks a lot. I will have a look!

**Comment by MatiasVara** [comment]
Hello, I am afraid I could not get time for this yet. Are you still interested?

**Comment by timKraeuter** [comment]
I think the videos and online resources are sufficient for now. I will let you know if I have concrete questions.

Thanks for your help!
